config/routes.rb
Rails.application.routes.draw do
    root 'home#index'
    get '/agenda' => 'agenda#index'
    get '/summary' => 'summary#index'
    get '/summary/week' => 'summary#week'
    get '/summary/month' => 'summary#month'
    get '/summary/year' => 'summary#year'
    get '/calendar' => 'calendar#index'
end

app/models/base_worktime.rb
class BaseWorktime < ActiveRecord::Base

  def self.expected_work_time day
    time = { hour: 0, min: 0, sec: 0 }
    miliseconds = find_by_week_day(day.strftime("%w").to_i + 1).work_time

    time[:sec], ms = miliseconds.divmod(1000)
    time[:min], time[:sec] = time[:sec].divmod(60)
    time[:hour], time[:min] = time[:min].divmod(60)
    time
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
    has_one :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :customer
  has_many :tasks
  has_many :time_records, as: :timeable
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :time_records, as: :timeable
end

app/models/time_record.rb
class TimeRecord < ActiveRecord::Base
    belongs_to :timeable, polymorphic: true
    def start_time
        DateTime.strptime(read_attribute(:start_time).to_s, '%Q')
    end

    def stop_time
        DateTime.strptime(read_attribute(:stop_time).to_s, '%Q')
    end

    def date_format
        start_time.to_date
    end

    def time_difference
        stop_time.to_time - start_time.to_time
    end
end

app/controllers/agenda_controller.rb
class AgendaController < ApplicationController
  helper ColorMapperHelper

  def index
    @records = TimeRecord.all.includes(:timeable)
    @records_by_date = @records.group_by(&:date_format)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

    @worked = TimeWork.worked_time_per_day @date, @records_by_date
    @expected_work = BaseWorktime.expected_work_time @date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :week_statistics, :week_graph, :today_statistics

  # needs improvement
  def week_graph
    # hardcoded value
    @project_week_stats ||= ProjectTimeWork.week_stats(Date.today)
    @current_week_stats ||= @project_week_stats.map {|entry| TimeWork.total_worked entry}
    @current_week_stats.map{ |entry| (entry[:sec] / 39600.0) * 100 }
  end

  def today_statistics
    day = Date.today.strftime("%w").to_i + 1
    @current_week_stats[day]
  end

  def week_statistics
    projects = TimeWork.worked_time_per_week @project_week_stats
    TimeWork.total_worked projects
  end

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @records = GraphData.calendar_data
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @projects = Project.all
    end

end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController

  before_filter :setup

  def index
    if params[:project_id].present?
      @projects = TaskTimeWork.worked_time_per_day @date
    else
      @projects = ProjectTimeWork.worked_time_per_day @date
    end
    @worked  = TimeWork.total_worked @projects
  end

  def week
    if params[:project_id].present?
      @week_stats = TaskTimeWork.week_stats @date
    else
      @week_stats = ProjectTimeWork.week_stats @date
    end
    @projects = TimeWork.worked_time_per_week @week_stats
    @worked = TimeWork.total_worked @projects
  end

  def month
    if params[:project_id].present?
      @month_stats = TaskTimeWork.month_stats @date
    else
      @month_stats = ProjectTimeWork.month_stats @date
    end
    @projects = TimeWork.worked_time_per_week @month_stats
    @worked = TimeWork.total_worked @projects
  end

  def year
    if params[:project_id].present?
      year_stats = TaskTimeWork.year_stats @date
    else
      year_stats = ProjectTimeWork.year_stats @date
    end
    @year_stats = TimeWork.year_stats_grouped year_stats
    @projects = TimeWork.worked_time_per_year @year_stats
    @worked = TimeWork.total_worked @projects
  end

  private

  # set date and project if task view
  def setup
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    if params[:project_id].present?
      @project = Project.find(params[:project_id])
      TaskTimeWork.set_project @project
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/color_mapper_helper.rb
MAPPINGS = {
  '-12877' => '#FFCDB3',
  '-26266' => '#FF9966',
  '-43776' => '#FF5500',
  '-5031168' => '#B33B00',
  '-10083840' => '#662200',

  '-19533' => '#FFB3B3',
  '-39322' => '#FF6666',
  '-65536' => '#FF0000',
  '-5046272' => '#B30000',
  '-10092544' => '#660000',

  '-19487' => '#FFB3E1',
  '-39230' => '#FF66C2',
  '-35382' => '#FF009A',
  '-5046164' => '#B3006C',
  '-10092483' => '#66003D',

  '-2509825' => '#D9B3FF',
  '-5019905' => '#B366FF',
  '-83883353' => '#8000FF',
  '-10878797' => '#5A00B3',
  '-13434778' => '#330066',

  '-4993537' => '#B3CDFF',
  '-10052865' => '#669AFF',
  '-16754945' => '#0056FF',
  '-16761677' => '#003CB3',
  '-16768410' => '#002266',

  '-4983809' => '#B3F3FF',
  '-10033409' => '#66E6FF',
  '-16722433' => '#00D5FF',
  '-16738893' => '#0095B3',
  '-16755354' => '#005566',

  '-4980787' => '#B3FFCD',
  '-10027111' => '#66FF99',
  '-16711851' => '#00FF55',
  '-16731333' => '#00B33B',
  '-16751070' => '#006622',

  '-1638477' => '#E6FFB3',
  '-3276954' => '#CDFF66',
  '-5505200' => '#ABFF00',
  '-8867072' => '#78B300',
  '-12294656' => '#446600',

  '-3149' => '#FFF3B3',
  '-6554' => '#FFE666',
  '-11008' => '#FFD500',
  '-5008128' => '#B39500',
  '-10070784' => '#665500',

  # aditional colors temp solution
  '-16776449' =>'#0081FF',
  '-13412609' =>'#33BCFF',
   '0' =>'#339AFF',

   '-25979' => '#FF9A85',
   '-10363' => '#FFD785',
   '-35021' => '#FF9966',
   '-19610' => '#FFB366',
   '-35021' => '#FFAE85',
   '-13210' => '#FFCC66',
   '-26317' => '#FFC285',

   '-15739' => '#FFC285',
   '-6554' => '#FFE666',
   '-13210' => '#FFCC66',
   '-5243' => '#FFEB85',
   '-10363' => '#FFD785',
   '-154' => '#FFFF66'

}

module ColorMapperHelper

  def color code
    MAPPINGS[code.to_s]
  end

  def color_type task
    task.is_a?(Project) ? color(task.color) : color(task.project.color)
  end

end

app/views/agenda/_tasks.html.erb
<%= content_tag :div, class: "box box-project box-project-success collapsed-box", style: "border-left: 10px solid #{color_type(task.timeable) }" do -%>
    <div class="box-header">
        <i class="fa fa-star"></i>
        <h3 class="box-title"><%= task.timeable.name %></h3> <br> |
            <small><%= task.timeable.project.name unless task.timeable.is_a?(Project) %> </small>
        <div class="pull-right timer spec">
            <p>
                <%= task.start_time.strftime("%I") %> : <%= task.start_time.strftime("%M") %>
                <small><%= task.start_time.strftime("%p") %> </small> -
                <%= task.stop_time.strftime("%I") %> : <%= task.stop_time.strftime("%M") %>
                <small><%= task.stop_time.strftime("%p") %></small>
            </p>
        </div>
    </div>
    <div class="box-body" style="display:none">
    </div>
<% end %>

app/views/agenda/index.html.erb
<!-- Top Navigation -->
<div class="box box-solid top-navigation">
    <div class="box-header">
    </div>
    <div class="box-body clearfix text-center">
     <div class="spec">
        <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe, date: @date.prev_day %> &nbsp;
        <%= @date.strftime("%A %d %B %Y") %> &nbsp;
        <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe, date: @date.next_day %>
     </div>
    </div>
</div><!-- /.box -->

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-12">
            <!-- Statistics -->
            <div class="box box-solid">
                <div class="box-header">
                </div>
                <div class="box-body clearfix text-center">
                    <div class="pull-left text-center">
                        <h4 class="spec">EXPECTED WORK TIME</h4>
                        <h4><%= '%02d' % @expected_work[:hour] %> <small>H&nbsp; </small>: <%= '%02d' % @expected_work[:min] %> <small>M</small></h4>                    </div>
                    <div class="pull-right text-center">
                        <h4 class="spec">HOURS WORKED</h4>
                        <h4><%= '%02d' % @worked[:hour] %> <small>H&nbsp; </small>: <%= '%02d' % @worked[:min] %> <small>M</small></h4>
                    </div>
                </div>
            </div><!-- /.box -->

            <!--  -->
            <% if @records_by_date[@date] %>
                <%= render :partial => 'tasks', :collection => @records_by_date[@date], :as => :task %>
            <% else %>
                <div class="box box-solid">
                    <div class="box-header">
                    </div>
                    <div class="box-body clearfix text-center">
                            <h4 class="spec">THERE ARE NO ENTRIES</h4>
                    </div>
                </div><!-- /.box -->
            <% end %>

        </section><!-- /.Left col -->
    </div><!-- /.row (main row) -->
</section><!-- /.content

app/views/calendar/index.html.erb
  <!-- Main content -->
  <section class="content">
      <div class="row">
          <div class="col-md-12">
            <%# @records %>
            <!-- Graph Data -->
            <%= content_tag :div, "", id: "calendar_chart", data: {calendar: @records } %>
              <div class="box box-primary">
                  <div class="box-body no-padding">
                      <!-- THE CALENDAR -->
                      <div id="full_calendar"></div>
                  </div><!-- /.box-body -->
              </div><!-- /. box -->
          </div><!-- /.col -->
      </div><!-- /.row -->
  </section><!-- /.content -->

app/views/home/index.html.erb
<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-12">

                <!-- Projects loop -->
            <% @projects.each do |project| %>
                <%= content_tag :div, class: "box box-project", style: "border-left: 10px solid #{color(project.color)};", data: {id: project.id,type: project.class.to_s} do %>
                    <div id: "timeable" class="box-header">
                        <i class="fa fa-star"></i>
                        <h3 class="box-title"><%= project.name %></h3>
                        <div class="pull-right box-tools">
                            <!-- button with a dropdown -->
                            <div class="btn-group">
                                <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                                <button class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i></button>
                                <ul class="dropdown-menu pull-right" role="menu">
                                    <li><a style="color:black" href="#">Settings</a></li>
                                </ul>
                            </div>
                        </div><!-- /. tools -->
                        <div class="spec pull-right timer">
                            <h5>00 <small>H&nbsp; </small>: 00 <small>M</small></h5>
                        </div>
                    </div>
                    <div id: "timeable" class="box-body clearfix">
                      <div class="spec pull-right">
                            <h4>00 <small>H&nbsp; </small>: 00 <small>M</small></h4>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="row">
                            <!-- Tasks loop -->
                            <% project.tasks.each do |task| %>
                                <%= content_tag :div, id: "timeable", class: "col-md-3 text-center", data: {id: task.id,type: task.class.to_s} do %>
                                    <div class="box-info box box-body"> <%= task.name %>  </div>
                                <% end %>
                            <% end %>
                        </div> <!-- /.row -->
                    </div>
                <% end %> <!-- /.box (chat box) -->
            <% end %>

        </section><!-- /.Left col -->
    </div><!-- /.row (main row) -->
</section><!-- /.content

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jiffy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body class="skin-black">

        <%= render 'shared/header' %>

        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <%= render 'shared/sidebar' %>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side strech">
              <%= yield %>
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->

</body>
</html>

app/views/shared/_header.html.erb
<!-- Left side column. contains the logo and sidebar -->
<header class="header">
    <a href="index.html" class="logo">
        <!-- Add the class icon to your logo image or logo icon to add the margining -->
        Jiffy
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span>Jane Doe <i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            <img src="<%= image_path("avatar3.png")%>" class="img-circle" alt="User Image" />
                            <p>
                                Jane Doe
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Info</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

app/views/shared/_sidebar.html.erb
<aside class="left-side sidebar-offcanvas collapse-left">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li><a>&nbsp;</a></li>
            <!-- Status Bars -->
            <li class="clearfix">
                <div class="box-body text-center">
                    <!-- future loop for week -->
                    <% week_graph.each do |day_stat| %>
                        <div class="progress vertical sm">
                            <div class="progress-bar progress-bar-aqua" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style='height: <%= day_stat%>%'>
                                <span class="sr-only">80%</span>
                            </div>
                        </div>
                    <% end %>
                </div><!-- /.box-body -->
            </li>
             <!-- Statistics -->
            <li>
                 <div class="box box-solid border-radius-none collapsed-box box-special" style="margin-bottom: 0px;">
                    <div class="box-header">
                        <small class="sm">TODAY</small>
                        <div class="box-tools pull-right">
                            <h4><%= today_statistics[:hour] %> <small>H&nbsp; </small>: <%= today_statistics[:min] %> <small>M</small></h4>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <!-- aorsitenaorsiten aosiretn -->
                    </div><!-- /.box-body -->
                 </div><!-- /.box -->
                 <div class="box box-solid border-radius-none collapsed-box box-special">
                    <div class="box-header">
                        <small class="sm">THIS WEEK</small>
                        <div class="box-tools pull-right">
                            <h4><%= week_statistics[:hour] %> <small>H&nbsp; </small>: <%= week_statistics[:min] %><small>M</small></h4>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <!-- aorsitenaorsiten aosiretn -->
                    </div><!-- /.box-body -->
                 </div><!-- /.box -->
            </li>

        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

app/views/shared/_tools.html.erb
<!-- Calendar -->
<li>
    <div class="box box-solid bg-green-gradient border-radius-none collapsed-box">
        <div class="box-header">
            <i class="fa fa-calendar"></i>
            <h3 class="box-title">Calendar</h3>
            <!-- tools box -->
            <div class="pull-right box-tools">
                <!-- button with a dropdown -->
                <div class="btn-group">
                    <button class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bars"></i></button>
                    <ul class="dropdown-menu pull-right" role="menu">
                        <li><a style="color:black" href="#">Add new event</a></li>
                        <li><a style="color:black" href="#">Clear events</a></li>
                        <li class="divider"></li>
                        <li><a style="color:black" href="#">View calendar</a></li>
                    </ul>
                </div>
                <button class="btn btn-success btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                <button class="btn btn-success btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>                                        
            </div><!-- /. tools -->
        </div><!-- /.box-header -->
        <div class="box-body no-padding" style='display:none;'>
            <!--The calendar -->
            <div id="calendar" style="width: 100%"></div>
        </div><!-- /.box-body -->  
    </div><!-- /.box -->                            
</li>
<!-- GRAPH -->
<li>
    <!-- solid sales graph -->
    <div class="box box-solid bg-teal-gradient border-radius-none collapsed-box" >
        <div class="box-header">
            <i class="fa fa-th"></i>
            <h3 class="box-title">Preview</h3>
            <div class="box-tools pull-right">
                <button class="btn bg-teal btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                <button class="btn bg-teal btn-sm" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body border-radius-none no-padding" style="display:none">
             <div class="chart" id="line-chart" style="height: 250px;"></div>                                     
        </div><!-- /.box-body -->
        <div class="box-footer no-border" style='display:none'>
            <div class="row">

                <div class="col-xs-4 text-center">
                    <input type="text" class="knob" data-readonly="true" value="30" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                    <div class="knob-label"></div>
                </div><!-- ./col -->
                <div class="col-xs-4 text-center">
                    <input type="text" class="knob" data-readonly="true" value="60" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                    <div class="knob-label"></div>
                </div><!-- ./col -->
                <div class="col-xs-4 text-center">
                    <input type="text" class="knob" data-readonly="true" value="90" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                    <div class="knob-label"></div>
                </div><!-- ./col -->
            </div><!-- /.row -->
        </div><!-- /.box-footer -->
    </div><!-- /.box -->     
</li>

app/views/summary/_graphs.html.erb
<div class="col-lg-6">
    <div class="box box-solid">
        <div class="box-header">
        </div>
        <div class="box-body clearfix text-center">
            <div class="col-lg-12">
                <div class="pull-left col-lg-8 text-center">
                    <div id="container_bar" style="width: 100%; height: 440px;"></div>
                </div>
                <div class="pull-right col-lg-4 text-center bar-stat">
                    <h5 class="spec">HOURS WORKED</h5>
                    <h4><%= '%02d' % @worked[:hour] %> <small>H&nbsp; </small>: <%= '%02d' % @worked[:min] %> <small>M</small></h4>
                </div>
            </div>
        </div>
    </div><!-- /.box -->
</div>

<div class="col-lg-6">
    <div class="box box-solid">
        <div class="box-header">
        </div>
        <div class="box-body clearfix text-center">
            <div id="container" style="width: 100%; height: 440px;"></div>
        </div>
    </div><!-- /.box -->
</div>

app/views/summary/_navigation.html.erb
<div class="nav-tabs-custom top-navigation">
    <ul class="nav nav-tabs pull-right">

                <%# if project.is_a?(Project) %>
        <li class="">
            <%= link_to url_for(date: @date) do %>
                <i class="fa fa-calendar"></i>
            <% end %>
        </li>

        <li class=""><%= link_to "Day", summary_path(date: @date.prev_day, project_id: params[:project_id]) %></li>
        <li class=""><%= link_to "Week", summary_week_path(date: @date.prev_day, project_id: params[:project_id]) %></li>
        <li class=""><%= link_to "Month", summary_month_path(date: @date.prev_day, project_id: params[:project_id]) %></li>
        <li class=""><%= link_to "Year", summary_year_path(date: @date.prev_day, project_id: params[:project_id]) %></li>

        <li class="pull-left header"><i class="fa fa-calendar-o"></i></li>

        <li class="pull-left nav-date-center">
            <div class="spec">
                <%= yield :content_nav %>
            </div>
        </li>
    </ul>
</div>
<% if params[:project_id].present? %>
    <%= content_tag :div, class: "nav-tabs-custom top-navigation", style: "background-color: #{color(@project.color)};" do %>
        <ul class="nav nav-tabs pull-right">
                <li class="pull-left header"><i class="fa fa-archive"></i></li>
                <li class="pull-left nav-project-center">
                    <div class="project">
                        <%= @project.name %>
                    </div>
                </li>
        </ul>
    <% end %>
<% end %>

app/views/summary/_project.html.erb
<div class="col-lg-6">
    <%= content_tag :div, class: "box box-project", style: "border-left: 10px solid #{color(project.color)};" do %>
        <div class="box-header">
            <i class="fa fa-star"></i>
            <h3 class="box-title"><%= project.name %></h3>
            <div class="pull-right box-tools">
            </div><!-- /. tools -->
            <div class="pull-right timer">
                <!-- <h4>29 <small style="color: white">H&nbsp; </small>: 22 <small style="color: white">M</small></h4> -->
            </div>
        </div>
        <div class="box-body clearfix">
            <div class="pull-right">
                <h4><%= '%02d' % worked[:hour] %> <small>H&nbsp; </small>: <%= '%02d' % worked[:min] %> <small>M</small></h4>
            </div>
        </div>
    <% end %> <!-- /.box (chat box) -->
</div>

app/views/summary/_setup_project.html.erb
<% projects.each do |project, worked| %>
    <% unless worked[:sec] == 00 %>
        <% if project.is_a?(Project) %>
            <%= link_to url_for(date: @date, project_id: project.id) do %>
                <%= render :partial => "project", :locals => {project: project, worked: worked} %>
            <% end %>
        <% else %>
            <%= render :partial => "project", :locals => {project: project, worked: worked} %>
        <% end %>
    <% end %>
<% end %>

app/views/summary/index.html.erb
<% content_for :content_nav do %>
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe,  summary_path(date: @date.prev_day, project_id: params[:project_id]) %> &nbsp;
    <%= @date.strftime("%d %A %B %Y") %> &nbsp;
    <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe,  summary_path(date: @date.next_day, project_id: params[:project_id])  %>
<% end %>

<!-- Calendar Tabs -->
<%= render 'navigation' %>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">

            <!-- Graph Data -->
            <%= content_tag :div, "", id: "projects_chart", data: {projects_pie: GraphData.data_pie(@projects),  projects_bar: [], value_fields: []  } %>

            <!-- Statistics -->
            <%= render 'graphs' %>

            <!-- Projects -->
            <%= render :partial => "setup_project", :locals => {:projects => @projects} %>

        </section><!-- /.Left col -->
    </div><!-- /.row (main row) -->
</section><!-- /.content

app/views/summary/month.html.erb
<% content_for :content_nav do %>
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe,  summary_month_path(date: @date.prev_month, project_id: params[:project_id]) %> &nbsp;
    <%= @date.strftime("%B %Y") %> &nbsp;
    <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe,  summary_month_path(date: @date.next_month, project_id: params[:project_id]) %> &nbsp;
<% end %>

<!-- Calendar Tabs -->
<%= render 'navigation' %>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">

            <!-- Graph Data -->
            <%= content_tag :div, "", id: "projects_chart", data: {projects_pie: GraphData.data_pie(@projects),  projects_bar: GraphData.data_bar(@month_stats), value_fields: GraphData.valueFields(@projects) } %>

            <!-- Statistics -->
            <%= render 'graphs' %>

            <!-- Projects -->
            <%= render :partial => "setup_project", :locals => {:projects => @projects} %>

        </section><!-- /.Left col -->
    </div><!-- /.row (main row) -->
</section><!-- /.content

app/views/summary/week.html.erb
<% content_for :content_nav do %>
    <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe,  summary_week_path(date: @date.prev_week, project_id: params[:project_id]) %> &nbsp;
    <%= @date.strftime("%A %B %Y") %> &nbsp;
    <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe,  summary_week_path(date: @date.next_week, project_id: params[:project_id]) %> &nbsp;
<% end %>

<!-- Calendar Tabs -->
<%= render 'navigation' %>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">

            <!-- Graph Data -->
            <%= content_tag :div, "", id: "projects_chart", data: {projects_pie: GraphData.data_pie(@projects),  projects_bar: GraphData.data_bar(@week_stats), value_fields: GraphData.valueFields(@projects)  } %>

            <!-- Statistics -->
            <%= render 'graphs' %>

            <!-- Projects -->
            <%= render :partial => "setup_project", :locals => {:projects => @projects} %>

        </section><!-- /.Left col -->
    </div><!-- /.row (main row) -->
</section><!-- /.content

app/views/summary/year.html.erb
 <% content_for :content_nav do %>
     <%= link_to "<i class='fa fa-arrow-left'></i>".html_safe,  summary_year_path(date: @date.prev_year, project_id: params[:project_id]) %> &nbsp;
    <%= @date.strftime("%Y") %> &nbsp;
     <%= link_to "<i class='fa fa-arrow-right'></i>".html_safe,  summary_year_path(date: @date.next_year, project_id: params[:project_id]) %> &nbsp;
<% end %>

<!-- Calendar Tabs -->
<%= render 'navigation' %>

<!-- Main content -->
<section class="content">
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable">

            <!-- Graph Data -->
            <%= content_tag :div, "", id: "projects_chart", data: {projects_pie: GraphData.data_pie(@projects),  projects_bar: GraphData.data_bar(@year_stats), value_fields: GraphData.valueFields(@projects) } %>

            <!-- Statistics -->
            <%= render 'graphs' %>

            <!-- Projects -->
            <%= render :partial => "setup_project", :locals => {:projects => @projects} %>

        </section><!-- /.Left col -->
    </div><!-- /.row (main row) -->
</section><!-- /.content